name: Build the rust project release

on:
  workflow_call:
    inputs:
        target:
          description: "Cross-compilation target required for your Rust project"
          type: string
          default: "x86_64-unknown-linux-gnu"

        archive-name:
          type: string
          default: archive

        archive-paths:
          description: "Paths of all files you need to archive"
          type: string
          required: true

        retention-days:
          description: "Archive retention period you need to set"
          type: number
          default: 1

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: setup toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: ${{ inputs.target }}

    - name: Install tools
      if: ${{ inputs.target }} == "x86_64-pc-windows-gnu"
      run: 
        sudo apt update && 
        sudo apt install -y mingw-w64

    - name: Release build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --target ${{ inputs.target }}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.archive-name }}
        path: ${{ inputs.archive-paths }}
        retention-days: ${{ inputs.retention-days }}